name: Docker as Root

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]
  workflow_dispatch:

jobs:
  docker-build:
    runs-on:  demo-dind-runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Print Hello World
      run: echo "Hello World"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      id: build
      uses: docker/build-push-action@v3
      with:
       context: .
       file: docker-images/busybox/Dockerfile
       tags: busy-box-image
       load: true
       network: host


