# runner.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: dind-rootless-runner
spec:
  repository: kiranshivalingegowda/arc-runner-repo
  containerMode: kubernetes
  serviceAccountName: dind-rootless-sa
    #serviceAccountName: actions-runner-controller
  labels:
   - dind-rootless-runner
  workVolumeClaimTemplate:
    storageClassName: "azuredisk-premium-retain"
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
  env: []
