githubConfigUrl: "https://github.com/kiranshivalingegowda/arc-runner-repo"
githubConfigSecret:
  github_token: "xxx"
runnerScaleSetName: "bootc-runner-scale-set"

containerMode:
  type: "kubernetes" ## type can be set to dind or kubernetes
  ## the following is required when containerMode.type=kubernetes
  kubernetesModeWorkVolumeClaim:
    accessModes: ["ReadWriteOnce"]
    # For local testing, use https://github.com/openebs/dynamic-localpv-provisioner/blob/develop/docs/quickstart.md to provide dynamic provision volume with storageClassName: openebs-hostpath
    storageClassName: "openebs-hostpath"
    resources:
      requests:
        storage: 1Gi

  spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
        securityContext:
          privileged: true
        env:
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "true"

