# runnerdeployment.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: demo-runner
spec:
  # This will deploy 2 runners now
  replicas: 2
  template:
    spec:
      repository: kiranshivalingegowda/arc-runner-repo
