apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dind-rootless-rb
  #namespace: default
  namespace: actions-runner-system
subjects:
- kind: ServiceAccount
  name: dind-rootless-sa
  #namespace: default
  namespace: actions-runner-system
roleRef:
  kind: Role
  name: dind-rootless-sa-role
  apiGroup: rbac.authorization.k8s.io
