name: Hello World

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Hello World
        run: echo "Hello World"

      - name: Build ISO
        id: build-iso
        uses: osbuild/bootc-image-builder-action@vX.Y.Z
        with:
          config-file: ./iso-config.toml
          image: quay.io/fedora/fedora-silverblue:latest
          types: |
            iso

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iso
          path: ${{ steps.build-iso.outputs.output-directory }}
          if-no-files-found: error
