name: Bootc VM

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Create ISO configuration
        run: |
          cat > iso-config.toml << EOF
          [[customizations.user]]
          name = "admin"
          password = "welcome"
          groups = ["wheel"]

          [[customizations.filesystem]]
          mountpoint = "/"
          minsize = "10 GiB"
          EOF

      - name: Build ISO
        id: build-iso
        uses: osbuild/bootc-image-builder-action@v0.0.2
        with:
          config-file: ./iso-config.toml
          image: quay.io/konflux-fedora/bootc-tenant/fedora-bootc-42-minimal:latest
          types: |
            iso

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iso
          path: ${{ steps.build-iso.outputs.output-directory }}
          if-no-files-found: error
