name: Bootc ARC

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: bootc-runner-scale-set
    container:
      #image: ubuntu:22.04
      image: quay.io/podman/stable:latest
      options: --privileged
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Podman Validation
        run: |
          podman --version
          pwd
          ls -ltra
          ls -ltra /var
          ls -ltra /var/lib
          ls -ltra /var/lib/containers

      - name: Create ISO configuration
        run: |
          cat > config.toml << EOF
          [[customizations.user]]
          name = "admin"
          password = "welcome"
          groups = ["wheel"]

          [[customizations.filesystem]]
          mountpoint = "/"
          minsize = "10 GiB"
          EOF

      - name: Podman Bootc image builder
        run: |

          # Ensure the image is fetched
          sudo podman pull quay.io/centos-bootc/centos-bootc:stream9
          mkdir output
          sudo podman run \
              --rm \
              -it \
              --privileged \
              --pull=newer \
              --security-opt label=type:unconfined_t \
              -v ./config.toml:/config.toml:ro \
              -v ./output:/output \
              #-v /var/lib/containers/storage:/var/lib/containers/storage \
              quay.io/centos-bootc/bootc-image-builder:latest \
              --type qcow2 \
            --use-librepo=True \
              quay.io/centos-bootc/centos-bootc:stream9
