name: Bootc ARC

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: bootc-runner-scale-set
    container:
     image: ubuntu:22.04
       #options: --privileged
    permissions:
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "Hello World"

